name = "ai-image-studio-worker"
main = "src/index.ts"
compatibility_date = "2025-05-15"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "typix-db"
database_id = "7ba8c436-fa0d-495b-b2bc-0bb014f54a0e"

[[r2_buckets]]
binding = "R2"
bucket_name = "typix-images"

[vars]
ENVIRONMENT = "development"
ALLOWED_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173"

[env.production]
vars = { ENVIRONMENT = "production", ALLOWED_ORIGINS = "https://ai-image-studio-frontend.pages.dev" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "typix-db"
database_id = "7ba8c436-fa0d-495b-b2bc-0bb014f54a0e"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "typix-images"
